# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\College\Other\PyProjects\PyTechnologicalRoute\ui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(584, 446)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.b_file_open = QtWidgets.QPushButton(self.centralwidget)
        self.b_file_open.setGeometry(QtCore.QRect(10, 10, 561, 31))
        self.b_file_open.setObjectName("b_file_open")
        self.l_head_text = QtWidgets.QLabel(self.centralwidget)
        self.l_head_text.setGeometry(QtCore.QRect(10, 50, 561, 341))
        self.l_head_text.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l_head_text.setFrameShape(QtWidgets.QFrame.Panel)
        self.l_head_text.setLineWidth(1)
        self.l_head_text.setScaledContents(False)
        self.l_head_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.l_head_text.setWordWrap(False)
        self.l_head_text.setObjectName("l_head_text")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 584, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())
        MainWindow.setWindowTitle("Файл")
        MainWindow.setFixedSize(584, 446)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.b_file_open.setText(_translate("MainWindow", "Open file"))
        self.l_head_text.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.menu.setTitle(_translate("MainWindow", "Меню"))
